"""
explanations.py
================
Builds the human-readable "why" behind a recommendation: why each asset
got the weight it did, and how risk tolerance, duration, and goal shaped
the overall allocation. Kept separate from the engine so wording can be
revised freely (or eventually generated by an LLM) without touching the
allocation math.
"""

from typing import List

from .models import InvestorProfile, AllocationItem
from .rules import ASSET_DESCRIPTIONS, RISK_REASONS, DURATION_REASONS, GOAL_REASONS


def explain_item(item: AllocationItem) -> str:
    """One sentence on why this specific asset class is in the portfolio."""
    return ASSET_DESCRIPTIONS[item.asset.value]


def explain_overall(profile: InvestorProfile) -> str:
    """Paragraph explaining how risk tolerance, duration, and goal combined
    to shape the allocation -- requirement 4 ("how risk level and duration
    affected the recommendation")."""
    risk = profile.risk_tolerance.value
    bucket = profile.duration_bucket()
    goal = profile.goal.value

    risk_text = RISK_REASONS[risk]
    duration_text = DURATION_REASONS[bucket].format(years=profile.duration_years)
    goal_text = GOAL_REASONS[goal]

    return "\n".join([risk_text, duration_text, goal_text])


def attach_explanations(items: List[AllocationItem]) -> None:
    """Mutates each AllocationItem in place, filling in `.explanation`."""
    for item in items:
        item.explanation = explain_item(item)
